// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Jyury11/skeleton/internal/ui"
	"github.com/Jyury11/skeleton/internal/write/commands"
	"github.com/Jyury11/skeleton/internal/write/domain/service"
	"github.com/Jyury11/skeleton/internal/write/infra"
)

// Injectors from wire.go:

// InitializeCLI DIコンテナ作成
func InitializeCLI() (*ui.Cobra, func(), error) {
	repository := infra.NewFileRepository()
	buildService := service.NewBuildService()
	convertService := service.NewConvertService(buildService)
	commandsCommands := commands.NewCommands(repository, convertService)
	handler := ui.NewHandler(commandsCommands)
	command := ui.NewRootCmd(handler)
	cobra := ui.NewCLI(command)
	return cobra, func() {
	}, nil
}
