// Code generated by skeleton; DO NOT EDIT.

package main
import (
	"context"

	"github.com/Jyury11/skeleton/example/dst/user/cmd/cli/di"
)

func main() {
	cli, clean, err := di.InitializeCLI()
	if err != nil {
		panic(err)
	}
	defer clean()

	ctx := context.Background()
	id := 99999
	if err := cli.Create(ctx, id); err != nil {
		panic(err)
	}
}
