// Code generated by skeleton; DO NOT EDIT.

package ui
import (
	"context"

	"github.com/jyury11/skeleton/example/dst/user/internal/usecase"
)

// Handler ...
type Handler struct {
	usecase *usecase.UseCases
}

// NewHandler ...
func NewHandler(usecase *usecase.UseCases) *Handler {
	return &Handler{usecase}
}

// Create ...
func (h *Handler) Create(ctx context.Context, id int) error {
	commands := usecase.NewCreateCommand(id)
	return h.usecase.CreateUseCase.Handle(ctx, commands)
}
