// Code generated by skeleton; DO NOT EDIT.

package di

import (
	"github.com/jyury11/skeleton/example/dst/user/internal/infra"
	"github.com/jyury11/skeleton/example/dst/user/internal/ui"
	"github.com/jyury11/skeleton/example/dst/user/internal/usecase"
)

// InitializeCLI Create DI Container
func InitializeCLI() (*ui.Handler, func(), error) {
	repository := infra.NewStdRepository()
	commandsCommands := usecase.NewUseCases(repository)
	handler := ui.NewHandler(commandsCommands)
	return handler, func() {
	}, nil
}
