// Code generated by skeleton; DO NOT EDIT.

package usecase
import (
	"github.com/jyury11/skeleton/example/dst/user/internal/repository"
)

// UseCases ...
type UseCases struct {
	CreateUseCase
}

// NewUseCases ...
func NewUseCases(repo repository.Repository) *UseCases {
	return &UseCases{
		CreateUseCase: NewCreate(repo),
	}
}
